epiverse-trace/epichains

.lintr
R/borel.r
R/checks.R
R/epichains.R
R/likelihood.R
R/simulate.r
R/stat_likelihoods.R
README.Rmd
man/aggregate.epichains.Rd
man/likelihood.Rd
man/simulate_summary.Rd
man/simulate_tree.Rd
man/simulate_tree_from_pop.Rd
tests/spelling.R
tests/testthat/tests-sim.r
vignettes/epichains.Rmd

This PR is a result of running `styler::style_pkg()` and `lintr::lint_pkg()` iteratively to fix all code style issues. The changes align with the [tidyverse style guide](https://style.tidyverse.org/index.html). 
Additionally, the `indentation_linter` is turned on to catch any indentation issues moving forward. It was [previously turned off](https://github.com/epiverse-trace/epichains/pull/33/commits/30ed39bde6c6b8633e1632b42a49faaeef3389c9) due to some instability issues but has been deemed necessary to be turned back on. 
The PR closes #40.

Fix code style across the package

---

.Rbuildignore
.github/workflows/pkgdown.yaml
.gitignore
DESCRIPTION
_pkgdown.yml

This PR sets up the package website and `pkgdown` workflows to conform with the Epiverse-TRACE {packagetemplate}. It closes #53.

Fix website

---

R/epichains.R

This PR fixes a bug in the `summary()` where the `max_time = -Inf` because the `<epichains>` object from `simulate_tree()` does not have a `time` column as a result of `serial_dist` not being specified. This closes #69.

Fix bug in summary method 

---

R/simulate.r

This PR removes a redundant `else` block from `simulate_tree_from_pop` that is already accounted for in the argument matching step and has an associated test.

Remove redundant else block

---

R/epichains.R
man/aggregate.epichains.Rd
tests/testthat/test-epichains.R
vignettes/epichains.Rmd

This PR closes #72 by removing the option to pass "both" to the `grouping_var` argument. 
This will prevent the issue raised in #79 where there is conditional inheritance in the `<epichains_aggregate_df>` class so that it can either be a subclass of `<data.frame>` or `<list>` depending on the value of `grouping_var`. 
The option for "both" was just for convenient but creates more problems than it solves.

Remove conditional inheritance from `aggregate` method

---

R/epichains.R
tests/testthat/test-epichains.R

This PR closes #80 by throwing an error when `aggregate(x, grouping_var = "both")` is called but the "time" column does not exist in the `<epichains>` object passed.

Improve `aggregate` method to deal with unavailable "time" column

---

README.Rmd
README.md
vignettes/epichains.Rmd

This PR:
* Simplifies the README by removing the function demonstrations and adding descriptions for each function and pointers to available vignettes. 
* Adds a "Getting Started" vignette with improved contents from the README.

Shorten README and add "Getting Started" vignette

---

R/likelihood.R

Order of operations at the end of likelihood() has been switched, which highlighted the opportunity to use a vectorized exp() call in some cases.
The new code should be:
``` r
library(microbenchmark)
library(epichains)
chain_sizes <- sample(1:10, 100, replace = TRUE)
microbenchmark(
likelihood(
chains = chain_sizes, statistic = "size",
offspring_dist = "pois", nsim_obs = 1e4, lambda = 0.5, obs_prob = 0.5
),
likelihood_old(
chains = chain_sizes, statistic = "size",
offspring_dist = "pois", nsim_obs = 1e4, lambda = 0.5, obs_prob = 0.5
),
times = 1e3
)
#> Unit: milliseconds
#>                                                                                                                                    expr
#>      likelihood(chains = chain_sizes, statistic = "size", offspring_dist = …
```

Sum loglikelihoods before exponentiating

---

R/epichains.R
R/simulate.r
man/head.epichains.Rd
man/likelihood.Rd
man/offspring_ll.Rd
man/simulate_summary.Rd
man/simulate_tree.Rd
man/simulate_tree_from_pop.Rd
man/tail.epichains.Rd
tests/testthat/_snaps/epichains.md
tests/testthat/test-epichains.R
tests/testthat/test-simulate.R

This PR:
- Renames the `ancestor` and `chain_id` columns of the `<epichains>` object to `infector_id` and `infectee_id`. This closes #92 
- Removes rownames from the `<epichains>` object to close #93.

Revise structure of returned `<epichains>` object

---

vignettes/epichains.Rmd

This PR is to replace the variable `grouping_var` by `by` in the call to `aggregate()`. The PR also increases the dimensions of the figure for better viewing.

Fix getting started vignette

---

R/epichains.R
man/epichains_summary.Rd
man/epichains_tree.Rd
man/new_epichains_summary.Rd
man/new_epichains_tree.Rd

This PR closes #161 by removing the empty defaults that were passed to the constructor and validation functions of `<epichains_tree>` and `<epichains_summary>` objects.

Remove defaults from class constructors and validators

---

_pkgdown.yml

This PR closes #168 by adding a pkgdown reference to the website for easier navigation of the exported functions.

Add pkgdown reference

---

.github/workflows/dependency-change.yaml
.github/workflows/lint-changed-files.yaml

This PR:
- Re-adds `lint-changed-files` workflow to be run at the package level because of some changes to GitHub policies that prevent us from using organization-wide workflows
- Adds the `dependency-change` workflow to check for changes in dependencies in PRs.

Add lint-changed-files and dependency-change workflows

---

.lintr

This PR closes #177 by updating the current `.lintr` file to use the configuration provided in the Epiverse-TRACE [`{packagetemplate}`](https://github.com/epiverse-trace/packagetemplate).

Add .lintr configuration from packagetemplate

---

R/epichains.R

This PR fixes #183 by replacing the use of `structure()` to construct a class. The lintr suggests using a call to `class()` followed by calls to `attr()`. 
This PR will be merged ahead of #182 to fix the CI warnings there.

Use class() and attr() instead of structure()

---

R/borel.r
R/epichains.R
R/simulate.r
R/stat_likelihoods.R
man/epichains_summary.Rd
man/epichains_tree.Rd
man/new_epichains_summary.Rd
man/new_epichains_tree.Rd
man/simulate_summary.Rd
tests/testthat/test-epichains.R
tests/testthat/test-simulate.R
vignettes/epichains.Rmd
vignettes/interventions.Rmd

This PR renames the `ntrees` argument to `index_cases` to help clarify the review comment in #158. The PR closes #158 and closes #186.

Rename `ntrees` argument to `index_cases` to clarify meaning

---

.lintr
R/simulate.r

This PR closes #196 and fixes #179 by restoring the cyclocomp_linter default limit of 15L and excluding `simulate_chains()` from the `cyclocomp_linter` run.
Further revisions in #194 will reduce the cyclomatic complexity as far as possible.

Restore cyclocomp_linter defaults

---

DESCRIPTION
R/simulate.r
README.md

The suggestions here come from investigating #179.
Indeed, the code here gives a cyclomatic complexity of 18. Some changes might be subjective preferences so feel free to cherry pick the changes you like.

Misc suggestions for simulate_chains()

---

R/helpers.R
tests/testthat/test-helpers.R

A failsafe to prevent bugs.
* **What is the current behaviour?** (You can also link to an open issue here)
The helper functions `.update_chain_stat()` and `.get_statistic_func()` used `switch()` statements that
did not error if there was no match. In fact, `switch()` statements return NULL if there is no match, which could potentially cause bugs downstream. However, the current state of the code is fine because in the function that it is called, the argument passed to it is matched at the top, and errors there.
* **What is the new behaviour (if this is a feature change)?**
The functions will now error when there is no match instead of returning `NULL`, which could cause bugs.
* **Does this PR introduce …

Make `switch()` statements error when there's no match

---

.github/workflows/dependabot.yml

This PR closes #206 by adding a dependabot actions to automatically update GHA versions. This is inspired by https://github.com/epiforecasts/EpiNow2/pull/513 and https://github.com/epinowcast/epinowcast/pull/354

Add dependabot workflow to update GitHub Actions versions

---

R/epichains.R
README.Rmd
README.md
man/summary.epichains_tree.Rd
tests/testthat/_snaps/epichains.md
tests/testthat/_snaps/simulate.md
tests/testthat/test-epichains.R
tests/testthat/test-simulate.R
vignettes/epichains.Rmd

* **Please check if the PR fulfils these requirements**
A feature.
* **What is the current behaviour?** (You can also link to an open issue here)
`summary.epichains_tree` method calculates the max generation, number of unique infectors from the `<epichains_tree>` object.
* **What is the new behaviour (if this is a feature change)?**
The `summary.epichains_tree` now returns `epichains_summary` with the same results as `simulate_summary()`
No, since this package is not released.
* **Other information**:
This PR closes #119.

Revise summary.epichains_tree to return <epichains_summary>

---

R/borel.r
man/rgborel.Rd
tests/testthat/tests-borel.r

This PR closes #191.
Bug fix.
* **What is the current behavior?** (You can also link to an open issue here)
`rborel()` returns an object of class `<epichains_summary>`
* **What is the new behavior (if this is a feature change)?**
`rborel()` now returns a numeric vector.
Not applicable.
* **Other information**:

Make `rborel()` return a numeric vector instead of an `<epichains_summary>` object

---

R/likelihood.R
man/likelihood.Rd

This PR closes #134 by moving `obs_prob` next to `nsim_obs` for logical flow in the arguments of `likelihood()`. This order makes sense because a user will have to specify `nsim_obs` if they change the default `obs_prob`.

Move `obs_prob` next to `nsim_obs` for logical flow in `likelihood()` signature

---

README.md
vignettes/interventions.Rmd

This PR closes #137 by adding a paragraph that links the intervention vignette here to that in {superspreading}.

Add paragraph linking to analogous vignette in {superspreading}

---

.github/workflows/render_readme.yml
README.md

This PR fixes the render-readme workflow and is not based on an issue raised. It does this by replacing the workflow here with the one in the Epiverse-TRACE {packagetemplate}, which has safe guards against failing render-readme workflows when the `README.md` file has been generated locally.

Fix render-readme: use workflow from `{packagetemplate}`

---

.github/dependabot.yml

This PR fixes the label option in the Dependabot workflow. It was wrongly specified as "package_infrastructure" instead of "pkg_infrastructrue".

dependabot workflow: Fix "label" option

---

R/likelihood.R
man/likelihood.Rd

This PR closes #231 by improving the documentation of `nsim_obs` and `obs_prob` so that it is clear that they are linked. The improvement also adds some interpretation to the arguments.

Improve documentation of `nsim_obs` and `obs_prob`

---

R/epichains.R
man/print.epichains_summary.Rd
tests/testthat/_snaps/epichains.md
tests/testthat/test-epichains.R

This PR closes #239.
Enhancement.
* **What is the current behavior?** (You can also link to an open issue here)
The summary method finds the max of only the finite values.
* **What is the new behavior (if this is a feature change)?**
The summary method now returns the max of all the values but prints the max as `>= stat_max` if the max was `Inf`.
NA
* **Other information**:

Make `summary` find max of all values including `Inf` and print `>= stat_max` if max is `Inf` 

---

vignettes/projecting_incidence.Rmd

This PR makes a minor correction to the vignette on projecting incidence where an object was referred to as `tf` instead of `t0`.

`tf` should be `t0` in vignette on projecting incidence 

---

R/simulate.r
vignettes/design-principles.Rmd

Remove nolint tags

---

.github/workflows/test-coverage.yaml

This PR updates the test coverage workflow to be in line with what is in packagetemplate following a fix that allows use of a global codecov token across the Epiverse-TRACE GitHub organisation (See https://github.com/epiverse-trace/packagetemplate/pull/152).

Update test coverage workflow to allow use of global codecov token

---

README.Rmd
README.md

This PR seeks to collapse the "Related Packages" section to reduce the amount of text in the README at a glance. The list can be accessed by clicking on "Click to expand". This will improve the focus of the README on the package's functionality.

Collapse the "Related Packages" section in the README

---

README.Rmd
README.md

This PR closes #262.
doc update
* **What is the current behavior?** (You can also link to an open issue here)
The current installation instructions suggest to use `pak` but that has known issues if the user has outdated or wrong GitHub credentials as has been noted in the linked issue and on the `pak` repository. See https://github.com/r-lib/pak/issues/504.
* **What is the new behavior (if this is a feature change)?**
We suggest to first try using `remotes` and if that fails, the user tries `pak` else file an issue.
No.
* …

Update installation instructions

---

NEWS.md
inst/WORDLIST
vignettes/branching_process_literature.Rmd
vignettes/design-principles.Rmd
vignettes/projecting_incidence.Rmd

Docs fix.
* **What is the current behavior?** (You can also link to an open issue here)
Some vignettes have pkgdown `as_is = TRUE` in their YAMLs. The reason was to allow the use of other features not provided by the HTML rendering format. See https://pkgdown.r-lib.org/reference/build_articles.html#output-formats.
* **What is the new behavior (if this is a feature change)?**
It removes the `as_is = TRUE` setting in the YAML headers of the vignettes as it reduces compatibility with incoming pkgdown versions.  
No
* **Other …

Remove pkgdown config `as_is = TRUE`

---

vignettes/interventions.Rmd
vignettes/theoretical_background.Rmd

In a previous PR #269, the setting `pkgdown: as_is` was removed from vignettes but this was incomplete. This PR follows up on the linked PR and removes others that were missed.

Remove missed pkgdown as_is = TRUE

---

_pkgdown.yml

This PR changes the `pkgdown` settings to render the website, showing the latest developments on the package after the most recent release and before the next release. Previously, we were rendering the released version, so all current developments were not showing up on the website.
The website rendering options are currently being discussed here https://github.com/epiverse-trace/blueprints/issues/100.

Use "unreleased" development mode for pkgdown

---

NEWS.md
README.Rmd
README.md
_pkgdown.yml

This PR changes the website mode to `auto` so that users can switch between the development and CRAN websites. A section has also been added to the README to mention the existence of the two websites.

Use `pkgdown` `auto` mode

---

README.Rmd
README.md

In #290, the README was updated to include a section with the package websites but the URLs were wrong. This PR follows up to fix that issue.

Fix wrong website URLs
